name: Process incoming article email

on:
  schedule:
    - cron: "0 7 * * *"   # daily 07:00 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          pip install openai

      - name: Process article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OUTPUT_EMAIL_USERNAME: ${{ secrets.OUTPUT_EMAIL_USERNAME }}
          OUTPUT_EMAIL_PASSWORD: ${{ secrets.OUTPUT_EMAIL_PASSWORD }}
          OUTPUT_EMAIL_TO: ${{ secrets.OUTPUT_EMAIL_TO }}
        run: python process_article.py
